package STAGE.stage.repositories;

import STAGE.stage.models.Stage;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface StageRepository extends JpaRepository<Stage, Long> {

    @Query("SELECT s FROM Stage s WHERE s.offre.entreprise.idEntreprise = :entrepriseId")
    List<Stage> findByOffre_EntrepriseId(Long entrepriseId);

    List<Stage> findByStatut(String statut); // Automatically generated by Spring Data JPA
}